#!/usr/bin/env bash
# shellcheck disable=SC1091,2154

set -e

# include common functions
. ./utils.sh

# GRID - disable icon copying, we already handled icons
# if [[ "${VSCODE_QUALITY}" == "insider" ]]; then
#   cp -rp src/insider/* vscode/
# else
#   cp -rp src/stable/* vscode/
# fi

# GRID - keep our license...
# cp -f LICENSE vscode/LICENSE.txt

cd vscode || { echo "'vscode' dir not found"; exit 1; }

../update_settings.sh

# GRID-SPECIFIC: Re-enabling patch application
# We need patches for branding (brand.patch) and other customizations
# generated by the builder logic
echo "Applying patches..."
if [[ "${CI_BUILD}" == "no" ]]; then
  # Local build - apply all patches
   ../dev/patch.sh
else
  # CI build - apply all patches but skip interactive conflict resolution
  # This relies on patches being clean

  # Copy patch helper
  cp ../dev/patch.sh ./apply_patches.sh
  chmod +x ./apply_patches.sh

  # We need to adapt patch.sh for CI usage or just loop through patches here
  # For now, let's use a simplified loop similar to patch.sh but non-interactive

  git config user.email "builder@grideditor.com"
  git config user.name "GRID Builder"

  # Apply helper/settings.patch first if it exists
  if [[ -f "../patches/helper/settings.patch" ]]; then
      git apply --reject "../patches/helper/settings.patch" || echo "Warning: settings.patch failed"
      git add .
      git commit -m "Apply settings.patch"
  fi

  # Apply all other patches
  for patch_file in ../patches/*.patch; do
      if [[ "$(basename "$patch_file")" == "brand.patch" ]]; then
          echo "Applying brand.patch..."
          # Replace !!APP_NAME!! placeholders if needed, but brand.patch seems to use them
          # logic to replace placeholders is likely needed either before or after
      fi

      echo "Applying $(basename "$patch_file")..."
      git apply --warn  "$patch_file" || echo "Warning: Failed to apply $patch_file"
      git add .
      git commit -m "Apply $(basename "$patch_file")"
  done
fi

echo "APP_NAME=\"${APP_NAME}\""
echo "APP_NAME_LC=\"${APP_NAME_LC}\""
echo "BINARY_NAME=\"${BINARY_NAME}\""
echo "GH_REPO_PATH=\"${GH_REPO_PATH}\""
echo "ORG_NAME=\"${ORG_NAME}\""

set -x

export ELECTRON_SKIP_BINARY_DOWNLOAD=1
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

if [[ "${OS_NAME}" == "linux" ]]; then
  export VSCODE_SKIP_NODE_VERSION_CHECK=1

   if [[ "${npm_config_arch}" == "arm" ]]; then
    export npm_config_arm_version=7
  fi
elif [[ "${OS_NAME}" == "windows" ]]; then
  if [[ "${npm_config_arch}" == "arm" ]]; then
    export npm_config_arm_version=7
  fi
else
  if [[ "${CI_BUILD}" != "no" ]]; then
    clang++ --version
  fi
fi

mv .npmrc .npmrc.bak
cp ../npmrc .npmrc

for i in {1..5}; do # try 5 times
  if [[ "${CI_BUILD}" != "no" && "${OS_NAME}" == "osx" ]]; then
    CXX=clang++ npm ci && break
  else
    npm ci && break
  fi

  if [[ $i == 3 ]]; then
    echo "Npm install failed too many times" >&2
    exit 1
  fi
  echo "Npm install failed $i, trying again..."

  sleep $(( 15 * (i + 1)))
done

mv .npmrc.bak .npmrc

setpath() {
  local jsonTmp
  { set +x; } 2>/dev/null
  jsonTmp=$( jq --arg 'path' "${2}" --arg 'value' "${3}" 'setpath([$path]; $value)' "${1}.json" )
  echo "${jsonTmp}" > "${1}.json"
  set -x
}

setpath_json() {
  local jsonTmp
  { set +x; } 2>/dev/null
  jsonTmp=$( jq --arg 'path' "${2}" --argjson 'value' "${3}" 'setpath([$path]; $value)' "${1}.json" )
  echo "${jsonTmp}" > "${1}.json"
  set -x
}

# product.json
cp product.json{,.bak}

setpath "product" "checksumFailMoreInfoUrl" "https://go.microsoft.com/fwlink/?LinkId=828886"
setpath "product" "documentationUrl" "https://grideditor.com/docs"
# setpath_json "product" "extensionsGallery" '{"serviceUrl": "https://open-vsx.org/vscode/gallery", "itemUrl": "https://open-vsx.org/vscode/item"}'
setpath "product" "introductoryVideosUrl" "https://go.microsoft.com/fwlink/?linkid=832146"
setpath "product" "keyboardShortcutsUrlLinux" "https://go.microsoft.com/fwlink/?linkid=832144"
setpath "product" "keyboardShortcutsUrlMac" "https://go.microsoft.com/fwlink/?linkid=832143"
setpath "product" "keyboardShortcutsUrlWin" "https://go.microsoft.com/fwlink/?linkid=832145"
setpath "product" "licenseUrl" "https://github.com/millsydotdev/GRID/blob/main/LICENSE"
# setpath_json "product" "linkProtectionTrustedDomains" '["https://open-vsx.org"]'
# setpath "product" "releaseNotesUrl" "https://go.microsoft.com/fwlink/?LinkID=533483#vscode"
setpath "product" "reportIssueUrl" "https://github.com/millsydotdev/GRID/issues/new"
setpath "product" "requestFeatureUrl" "https://github.com/millsydotdev/GRID/issues/new"
setpath "product" "tipsAndTricksUrl" "https://go.microsoft.com/fwlink/?linkid=852118"
setpath "product" "twitterUrl" "https://x.com/grid_editor"

if [[ "${DISABLE_UPDATE}" != "yes" ]]; then
  setpath "product" "updateUrl" "https://grideditor.com/api/update"
  setpath "product" "downloadUrl" "https://grideditor.com"
fi

if [[ "${VSCODE_QUALITY}" == "insider" ]]; then
  setpath "product" "nameShort" "GRID Insiders"
  setpath "product" "nameLong" "GRID Insiders"
  setpath "product" "applicationName" "grid-insiders"
  setpath "product" "dataFolderName" ".grid-insiders"
  setpath "product" "linuxIconName" "grid-insiders"
  setpath "product" "quality" "insider"
  setpath "product" "urlProtocol" "grid-insiders"
  setpath "product" "serverApplicationName" "grid-server-insiders"
  setpath "product" "serverDataFolderName" ".grid-server-insiders"
  setpath "product" "darwinBundleIdentifier" "com.grid.ide.insiders"
  setpath "product" "win32AppUserModelId" "GRID.IDE.Insiders"
  setpath "product" "win32DirName" "GRID Insiders"
  setpath "product" "win32MutexName" "grid-insiders"
  setpath "product" "win32NameVersion" "GRID Insiders"
  setpath "product" "win32RegValueName" "grid-insiders"
  setpath "product" "win32ShellNameShort" "GRID Insiders"
  setpath "product" "win32AppId" "{{5893CE20-77AA-4856-A655-ECE65CBCF1C7}"
  setpath "product" "win32x64AppId" "{{7A261980-5847-44B6-B554-31DF0F5CDFC9}"
  setpath "product" "win32arm64AppId" "{{EE4FF7AA-A874-419D-BAE0-168C9DBCE211}"
  setpath "product" "win32UserAppId" "{{FA3AE0C7-888E-45DA-AB58-B8E33DE0CB2E}"
  setpath "product" "win32x64UserAppId" "{{5B1813E3-1D97-4E00-AF59-C59A39CF066A}"
  setpath "product" "win32arm64UserAppId" "{{C2FA90D8-B265-41B1-B909-3BAEB21CAA9D}"
else
  setpath "product" "nameShort" "GRID"
  setpath "product" "nameLong" "GRID"
  setpath "product" "applicationName" "grid"
  setpath "product" "linuxIconName" "grid"
  setpath "product" "quality" "stable"
  setpath "product" "urlProtocol" "grid"
  setpath "product" "serverApplicationName" "grid-server"
  setpath "product" "serverDataFolderName" ".grid-server"
  setpath "product" "darwinBundleIdentifier" "com.grid.ide"
  setpath "product" "win32AppUserModelId" "GRID.IDE"
  setpath "product" "win32DirName" "GRID"
  setpath "product" "win32MutexName" "grid"
  setpath "product" "win32NameVersion" "GRID"
  setpath "product" "win32RegValueName" "GRID"
  setpath "product" "win32ShellNameShort" "GRID"
  # GRID - already set in product
  # setpath "product" "win32AppId" "{{88DA3577-054F-4CA1-8122-7D820494CFFB}"
  # setpath "product" "win32x64AppId" "{{9D394D01-1728-45A7-B997-A6C82C5452C3}"
  # setpath "product" "win32arm64AppId" "{{0668DD58-2BDE-4101-8CDA-40252DF8875D}"
  # setpath "product" "win32UserAppId" "{{0FD05EB4-651E-4E78-A062-515204B47A3A}"
  # setpath "product" "win32x64UserAppId" "{{8BED5DC1-6C55-46E6-9FE6-18F7E6F7C7F1}"
  # setpath "product" "win32arm64UserAppId" "{{F6C87466-BC82-4A8F-B0FF-18CA366BA4D8}"
fi

jsonTmp=$( jq -s '.[0] * .[1]' product.json ../product.json )
echo "${jsonTmp}" > product.json && unset jsonTmp

cat product.json

# package.json
cp package.json{,.bak}

setpath "package" "version" "${RELEASE_VERSION%-insider}"

replace 's|Microsoft Corporation|GRID Editor|' package.json

cp resources/server/manifest.json{,.bak}

if [[ "${VSCODE_QUALITY}" == "insider" ]]; then
  setpath "resources/server/manifest" "name" "GRID Insiders"
  setpath "resources/server/manifest" "short_name" "GRID Insiders"
else
  setpath "resources/server/manifest" "name" "GRID"
  setpath "resources/server/manifest" "short_name" "GRID"
fi

cp resources/server/manifest.json{,.bak}

if [[ "${VSCODE_QUALITY}" == "insider" ]]; then
  setpath "resources/server/manifest" "name" "GRID Insiders"
  setpath "resources/server/manifest" "short_name" "GRID Insiders"
else
  # GRID already has this
  setpath "resources/server/manifest" "name" "GRID"
  setpath "resources/server/manifest" "short_name" "GRID"
fi

# announcements
# replace "s|\\[\\/\\* BUILTIN_ANNOUNCEMENTS \\*\\/\\]|$( tr -d '\n' < ../announcements-builtin.json )|" src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts

../undo_telemetry.sh

replace 's|Microsoft Corporation|GRID Editor|' build/lib/electron.js
replace 's|Microsoft Corporation|GRID Editor|' build/lib/electron.ts
replace 's|([0-9]) Microsoft|\1 GRID|' build/lib/electron.js
replace 's|([0-9]) Microsoft|\1 GRID|' build/lib/electron.ts

if [[ "${OS_NAME}" == "linux" ]]; then
  # microsoft adds their apt repo to sources
  # unless the app name is code-oss
  # as we are renaming the application to grid
  # we need to edit a line in the post install template
  if [[ "${VSCODE_QUALITY}" == "insider" ]]; then
    sed -i "s/code-oss/grid-insiders/" resources/linux/debian/postinst.template
  else
    sed -i "s/code-oss/grid/" resources/linux/debian/postinst.template
  fi

  # fix the packages metadata
  # code.appdata.xml
  sed -i 's|Visual Studio Code|GRID|g' resources/linux/code.appdata.xml
  sed -i 's|https://code.visualstudio.com/docs/setup/linux|https://grideditor.com|' resources/linux/code.appdata.xml
  sed -i 's|https://code.visualstudio.com/home/home-screenshot-linux-lg.png|https://grideditor.com/img/grid-screenshot.png|' resources/linux/code.appdata.xml
  sed -i 's|https://code.visualstudio.com|https://grideditor.com|' resources/linux/code.appdata.xml

  # control.template
  sed -i 's|Microsoft Corporation <vscode-linux@microsoft.com>|GRID Team <team@grideditor.com>|'  resources/linux/debian/control.template
  sed -i 's|Visual Studio Code|GRID|g' resources/linux/debian/control.template
  sed -i 's|https://code.visualstudio.com/docs/setup/linux|https://grideditor.com|' resources/linux/debian/control.template
  sed -i 's|https://code.visualstudio.com|https://grideditor.com|' resources/linux/debian/control.template

  # code.spec.template
  sed -i 's|Microsoft Corporation|GRID Team|' resources/linux/rpm/code.spec.template
  sed -i 's|Visual Studio Code Team <vscode-linux@microsoft.com>|GRID Team <team@grideditor.com>|' resources/linux/rpm/code.spec.template
  sed -i 's|Visual Studio Code|GRID|' resources/linux/rpm/code.spec.template
  sed -i 's|https://code.visualstudio.com/docs/setup/linux|https://grideditor.com|' resources/linux/rpm/code.spec.template
  sed -i 's|https://code.visualstudio.com|https://grideditor.com|' resources/linux/rpm/code.spec.template

  # snapcraft.yaml
  sed -i 's|Visual Studio Code|GRID|'  resources/linux/rpm/code.spec.template
elif [[ "${OS_NAME}" == "windows" ]]; then
  # code.iss
  sed -i 's|https://code.visualstudio.com|https://grideditor.com|' build/win32/code.iss
  sed -i 's|Microsoft Corporation|GRID Editor|' build/win32/code.iss
fi

cd ..
